language: ruby
rvm: 2.5.3
sudo: false
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

# before_cache:
#  - rm -rf ./_site # Cleaning up...

bundler_args: --without development

cache:
  bundler: true # vendor/bundle
  directories:
    - node_modules # NPM packages

before_install:
  - npm install

# install
#  - bundle install --without development

before_script:
  - npm install

script:
  - npm run build
  - bundle exec jekyll build --config _config.yml,_config_test.yml # Building site...
#  - bundle exec htmlproofer ./_site --only-4xx # Checking site...
#  - bundle exec github-pages health-check # Checking DNS... (Should have CNAME file)
  - rm -rf ./_site # Cleaning up...

branches:
  only:
    - master

git:
  depth: 10
