language: ruby
rvm:
  - 2.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

# before_cache:
#  - rm -rf ./_site # Cleaning up...

bundler_args: --without development

cache:
  bundler: true # vendor/bundle
  directories:
    - node_modules # NPM packages

before_install:
  - npm install

# install
#  - bundle install --without development

before_script:
  - npm install -g gulp

script:
  - gulp
  - bundle exec jekyll build # Building site...
  - bundle exec htmlproofer ./_site --only-4xx # Checking site...
#  - bundle exec github-pages health-check # Checking DNS... (Should have CNAME file)
  - rm -rf ./_site # Cleaning up...

branches:
  only:
    - master

git:
  depth: 10
