# GitHub Pages (https://pages.github.com/versions/)
# Ruby version
language: ruby
rvm:
  - 2.5.8

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - bundle exec github-pages versions # List dependency versions
  - bundle exec github-pages health-check # Checking DNS... (Should have CNAME file)
  - bundle exec jekyll build --config _config.yml,_config_test.yml --profile # Building site...
  - bundle exec jekyll doctor # Checking Jekyll configuration
  - bundle exec htmlproofer ./_site --allow-hash-href --assume-extension --http-status-ignore "403,429" --only-4xx # Checking site...
  - bundle exec jekyll clean # Cleaning up...

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

cache: bundler

git:
  depth: 10

notifications:
  email: false
