language: ruby
rvm: 2.5.3
sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

# before_cache:
#  - rm -rf ./_site # Cleaning up...

# bundler_args: --without development

cache:
  bundler: true # vendor/bundle
  directories:
    - node_modules # NPM packages

before_install:
  - rm -rf ./_site ./node_modules # Cleaning up...

install:
  - npm install
  - bundle intall

before_script:
  - npm run build

script:
  - bundle exec github-pages versions # List dependency versions
  - bundle exec github-pages health-check # Checking DNS... (Should have CNAME file)
  - bundle exec jekyll build --config _config.yml,_config_test.yml # Building site...
  - bundle exec htmlproofer --assume-extension --only-4xx --http-status-ignore "403,429" ./_site # Checking site...
  - rm -rf ./_site # Cleaning up...

branches:
  only:
    - master

git:
  depth: 10

notifications:
  email: false
