language: ruby
rvm:
  - 2.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
cache: bundler

script:
  - title "Building site..."
  - bundle exec jekyll build
  - title "Checking site..."
  - bundle exec htmlproofer ./_site --only-4xx
  - title "Checking DNS..."
  - bundle exec github-pages health-check
  - title "Cleaning up..."
  - rm -rf _site

branches:
  only:
    - master

git:
  depth: 10
