# Jekyll configuration (https://jekyllrb.com/docs/configuration/)

# Coding guide
# camelCase for JavaScript, underscores for Liquid tag, and hyphens for CSS.

# ----------------------------------------------------------------------
# | Site settings                                                      |
# ----------------------------------------------------------------------

# URL of site, include http(s)://, do not include a trailing slash
url: "https://kshitizaryal.com.np"

title: "Kshitiz Aryal"
# tagline: "Follow me across the interwebs."
tagline: "Keepin&apos; it real since 1999🔥"
description: "Hey -- this is Kshitiz Aryal, who loves traveling new places and listening music a lot."
logo: "/assets/img/avatar.png"
repository: "KshitizAryal/kshitizaryal.github.io"
branch: "master"

author:
  name: "Kshitiz Aryal"
#  email: "#"
  uri: "https://twitter.com/KshitizAryal"
  avatar: "/assets/img/avatar.png"
  bio: "Life is like riding a bike. To keep your balance, you must keep moving."
  gender: "Male"
  nationality: "Nepal"
  twitter: "KshitizAryal"
  github: "KshitizAryal"
  facebook: "KshitizAryal"
  instagram: "considerkshitiz"

# Google Analytics ID
google_analytics_id: "UA-120293538-1"

# SEO
twitter:
  username: "KshitizAryal"
  card: summary
# SEO JSON-LD
social:
  name: "Kshitiz Aryal"
  links:
    - https://twitter.com/KshitizAryal
    - https://github.com/KshitizAryal
    - https://www.facebook.com/KshitizAryal
    - https://www.instagram.com/ConsiderKshitiz

# ----------------------------------------------------------------------
# | Build settings                                                     |
# ----------------------------------------------------------------------

encoding: "utf-8"
timezone: "Asia/Kathmandu"
# lang: "en-US"

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/img/avatar.png"

# sass:
#  sass_dir: _sass
#  style: :compressed

compress_html:
  clippings: all
  comments: all
  ignore:
    envs: development
  profile: false

plugins:
# - jekyll-feed
# - jekyll-gist
  - jekyll-github-metadata
# - jekyll-mentions
# - jekyll-paginate
# - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
# - jemoji

include: ["_pages"]

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - script
  - scripts
  - src
  - banner.js
  - postcss.config.js
  - package.json
  - package-lock.json
  - npm-debug.log
  - node_modules
  - vendor
  - bundle
  - ".bundle"
  - ".cache"
  - ".sass-cache"
  - ".jekyll-cache"
  - ".jekyll-metadata"
  - ".browserslistrc"
  - ".editorconfig"
  - ".eslintignore"
  - ".eslintrc.json"
  - ".gitattributes"
  - ".gitignore"
  - ".stylelintignore"
  - ".stylelintrc.json"
  - ".travis.yml"
