# Jekyll config file http://jekyllrb.com/docs/configuration/

# ----------------------------------------------------------------------
# | Site settings                                                      |
# ----------------------------------------------------------------------

# URL of site, include http(s)://, do not include a trailing slash
url: "https://kshitizaryal.github.io"

name: "Kshitiz Aryal"
description: "Follow me across the interwebs."
icon: "/assets/img/k-icon-white-on-teal.png"
repository: KshitizAryal/kshitizaryal.github.io

social:
  - title: Twitter
    url: https://twitter.com/KshitizAryal
    fa: twitter

  - title: Facebook
    url: https://www.facebook.com/kshitiz.aryal
    fa: facebook

  - title: Instagram
    url: https://instragram.com/considerkshitiz
    fa: instagram

  - title: Tumblr
    url: http://kshitizaryal.tumblr.com
    fa: tumblr

# Google Analytics ID
google_analytics_id: "UA-62011938-1"

# Google Maps API Key and local location
google_map:
  api: "AIzaSyBRfaWsUPFLarp7efMqyne-1K7uigYPtyQ"
  zoom: 13
  latitude: "27.7089603"
  longitude: "85.3261328"


# ----------------------------------------------------------------------
# | Build settings                                                     |
# ----------------------------------------------------------------------

encoding: "utf-8"
timezone: Asia/Kathmandu
locale: en_us
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 1..3

highlighter: rouge

gist:
  noscript: false

sass:
#  sass_dir: _sass
  style: :compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false

include: ["_pages"]

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - src
  - node_modules
  - package.json
  - Gruntfile.js
  - vendor
  - bower.json

# Plugins
gems:
#  - jekyll-feed
#  - jekyll-github-metadata
#  - jekyll-mentions
#  - jekyll-redirect-from
#  - jekyll-seo-tag
  - jekyll-sitemap
#  - jemoji
