# ----------------------------------------------------------------------
# | For Travis CI test                                                 |
# ----------------------------------------------------------------------

url: "http://localhost:4000"
github:
  repository_nwo: "KshitizAryal/kshitizaryal.github.io"
  owner_url: "https://github.com/KshitizAryal"
  repository_url: "https://github.com/KshitizAryal/kshitizaryal.github.io"
