# ----------------------------------------------------------------------
# | For local development                                              |
# ----------------------------------------------------------------------
#
# Getting started with Jekyll using default config (_config.yml):
#
# 1. Install Ruby
# 2. $ gem install bundler
# 3. $ cd ./kshitizaryal.github.io
# 4. $ bundle Install
# 5. $ bundle exec jekyll build
#
#
# Override config (_config_dev.yml) for local development test:
#
# - Build site
#   $ bundle exec jekyll build --config _config.yml,_config_dev.yml
#
# - Build site and watch changes
#   $ bundle exec jekyll build --config _config.yml,_config_dev.yml --watch
#
# - Serve site http://localhost:4000
#   $ bundle exec jekyll serve --config _config.yml,_config_dev.yml

# https://jekyllrb.com/docs/configuration/environments/

url: "http://localhost:4000"
github:
  url: "http://localhost:4000"
google_analytics_id: ""
