# Jekyll config file http://jekyllrb.com/docs/configuration/

# ----------------------------------------------------------------------
# | Site settings                                                      |
# ----------------------------------------------------------------------

# URL of site, include http(s)://, do not include a trailing slash
url: "https://kshitizaryal.com.np"

name: "Kshitiz Aryal"
description: "Follow me across the interwebs."
icon: "/assets/img/k-icon-white-on-teal.png"
repository: KshitizAryal/kshitizaryal.github.io

author:
  name: "Kshitiz Aryal"
  email: "kshitizcares@gmail.com"
  uri: "https://twitter.com/MilanAryal"
  avatar: "/assets/img/k-icon-white-on-teal.png"
  bio: "Follow me across the interwebs."
  facebook: kshitizaryal
  twitter: KshitizAryal
  google_plus: KshitizAryal
  instagram: considerkshitiz
  street: "Chandragiri 15"
  locality: Kathmandu
  region: Bagmati
  country: Nepal
  postcode: 44600

# Google Analytics ID
google_analytics_id: "UA-62011938-1"


# ----------------------------------------------------------------------
# | Build settings                                                     |
# ----------------------------------------------------------------------

encoding: "utf-8"
timezone: Asia/Kathmandu
locale: en_us
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 1..3

highlighter: rouge

gist:
  noscript: false

# sass:
#  sass_dir: _sass
#  style: :compressed

compress_html:
  clippings: all
  comments: all
  profile: false

include: ["_pages"]

# Plugins
gems:
# - jekyll-feed
# - jekyll-gist
  - jekyll-github-metadata
# - jekyll-mentions
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
  - jekyll-sitemap
# - jemoji

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - gulpfile.js
  - package.json
  - npm-debug.log
  - node_modules
  - vendor
  - bundle
  - ".bundle"
  - ".sass-cache"
  - src
