# Jekyll config file http://jekyllrb.com/docs/configuration/

# ----------------------------------------------------------------------
# | Site settings                                                      |
# ----------------------------------------------------------------------

# URL of site, include http(s)://, do not include a trailing slash
url: "https://kshitizaryal.com.np"

title: "Kshitiz Aryal"
description: "Follow me across the interwebs."
logo: "/assets/img/avatar.png"
repository: KshitizAryal/kshitizaryal.github.io

author:
  name: "Kshitiz Aryal"
#  email: "#"
  uri: "https://twitter.com/KshitizAryal"
  avatar: "/assets/img/avatar.png"
  bio: "Life is like riding a bike. To keep your balance, you must keep moving."
  facebook: KshitizAryal
  twitter: KshitizAryal
  instagram: considerkshitiz
#  street: "#"
#  locality: "#"
#  region: "#"
  country: Nepal
#  postcode: "#"

# Google Analytics ID
google_analytics_id: "UA-120293538-1"


# ----------------------------------------------------------------------
# | Build settings                                                     |
# ----------------------------------------------------------------------

encoding: "utf-8"
timezone: Asia/Kathmandu
locale: en_us
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 1..3

highlighter: rouge

gist:
  noscript: false

# sass:
#  sass_dir: _sass
#  style: :compressed

compress_html:
  clippings: all
  comments: all
  profile: false

include: ["_pages"]

# Plugins
gems:
# - jekyll-feed
# - jekyll-gist
  - jekyll-github-metadata
# - jekyll-mentions
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
  - jekyll-sitemap
# - jemoji

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - gulpfile.js
  - package.json
  - npm-debug.log
  - node_modules
  - vendor
  - bundle
  - ".bundle"
  - ".sass-cache"
  - src
