name: My workflow
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec github-pages versions # List dependency versions
    - run: bundle exec github-pages health-check # Checking DNS... (Should have CNAME file)
    - run: bundle exec jekyll build --config _config.yml,_config_test.yml --profile # Building site...
    - run: bundle exec jekyll doctor # Checking Jekyll configuration
    - run: bundle exec htmlproofer ./_site --allow-hash-href --assume-extension --http-status-ignore "403,429" --only-4xx # Checking site...
    - run: bundle exec jekyll clean # Cleaning up...
