# Workflow for building and deploying a Hugo site to GitHub Pages
# https://github.com/actions/starter-workflows/blob/main/pages/hugo.yml
name: pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths-ignore:
      - "**"
      - "!.github/workflows/**"
      - "!hugo.yml"
      - "!src/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: "0.133.1"

    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Version info
        run: |
          hugo version

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Hugo
        env:
          HUGO_ENV: production
        # Outputs to the './_site' directory by default
        run: |
          hugo \
            --cleanDestinationDir \
            --minify

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3
        if: ${{ success() && github.repository == 'kshitizaryal/kshitizaryal.github.io' && github.ref == 'refs/heads/main' }}
        with:
          path: ./_site/

  # Deployment job
  deploy:
    name: deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.repository == 'kshitizaryal/kshitizaryal.github.io' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: ${{ success() }}
