name: My workflow

on:
  push:
    branches:
      - main

env:
  RUBY_VERSION: 2.7.1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }} # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: List dependency versions
        run: bundle exec github-pages versions

      # - name: Checking DNS # Should have CNAME file
      #  run: bundle exec github-pages health-check

      - name: Checking Jekyll configuration
        run: bundle exec jekyll doctor

      - name: Building site
        run: bundle exec jekyll build --config _config.yml,_config_test.yml --profile

      - name: Checking HTML files
        run: bundle exec htmlproofer ./_site --allow-hash-href --assume-extension --check-external-hash --check-img-http --internal-domains "kshitizaryal.github.io" --http-status-ignore "403,429" --only-4xx

      - name: Cleaning up
        run: bundle exec jekyll clean
